#!/bin/bash

# display configuration
readonly DISPLAY1=eDP-1
readonly DISPLAY2=HDMI-1
readonly GAMMA=1:0.93853986:0.88130458

xrandr --output $DISPLAY1 --primary \
       --output $DISPLAY2 --right-of $DISPLAY1

xrandr --output $DISPLAY1 --brightness .7 --gamma $GAMMA
xrandr --output $DISPLAY2 --brightness .7 --gamma $GAMMA

bspc monitor $DISPLAY1 -d i ii iii iv v
bspc monitor $DISPLAY2 -d i ii iii iv v

# window manager
bspc config border_width 2
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config active_border_color "#0055a5"
bspc config focused_border_color "#0055a5"
bspc config pointer_follows_monitor true
bspc config presel_feedback_color "#0055a5"
bspc config -m $DISPLAY1 split_ratio 0.6
bspc config -m $DISPLAY2 split_ratio 0.6

# external rules
bspc config external_rules_command $HOME/.config/bspwm/external-rules.sh

# rules
$HOME/.config/bspwm/rules.sh

# focus on primary monitor
bspc monitor -f primary

# disable screensaver
xset s off
xset -dpms
xset s noblank

# set keyboard repeat rate
xset r rate 260 55

# set wallpaper
feh --bg-center $HOME/.local/share/wallpapers/kiss.jpg --image-bg "#23262d"

# applications
picom &
setxkbmap -layout us -variant altgr-intl
sxhkd ~/.config/sxhkd/*.conf &
numlockx
$HOME/.config/polybar/launch.sh

# alexa standby
while xset -q &>/dev/null; do
    play -n synth 1 sin 0
    sleep 300
done
